import * as fs from 'fs';
import * as path from 'path';

console.log('⚙️ Starting CSS Variables Transpilation (Multi-Mode)...');

const CONTRACTS_DIR = path.resolve(__dirname, '../../contracts');
const OUTPUT_FILE = path.resolve(__dirname, '../../guideline/tokens.css');

// JSONの読み込み
const primitive = JSON.parse(fs.readFileSync(path.join(CONTRACTS_DIR, 'tokens/primitive.json'), 'utf8'));
const semanticLight = JSON.parse(fs.readFileSync(path.join(CONTRACTS_DIR, 'tokens/semantic-light.json'), 'utf8'));
const semanticDark = JSON.parse(fs.readFileSync(path.join(CONTRACTS_DIR, 'tokens/semantic-dark.json'), 'utf8'));
const button = JSON.parse(fs.readFileSync(path.join(CONTRACTS_DIR, 'components/button.json'), 'utf8'));

// 1. 各レイヤーのフラット化
function flattenTokens(obj: any, prefix = ''): Record<string, string> {
  const result: Record<string, string> = {};
  for (const key in obj) {
    if (obj.hasOwnProperty(key)) {
      const val = obj[key];
      const newKey = prefix ? `${prefix}-${key}` : key;
      if (val && typeof val === 'object' && '$value' in val) {
        result[newKey] = val.$value;
      } else if (val && typeof val === 'object') {
        Object.assign(result, flattenTokens(val, newKey));
      }
    }
  }
  return result;
}

const flatPrimitive = flattenTokens(primitive);
const flatSemanticLight = flattenTokens(semanticLight);
const flatSemanticDark = flattenTokens(semanticDark);
const flatButton = flattenTokens(button.tokens, 'button');

// 2. エイリアスの解決
function resolveAlias(value: string, dictionary: Record<string, string>): string {
  const match = value.match(/^\{(.+)\}$/);
  if (match) {
    const aliasKey = match[1].replace(/\./g, '-');
    if (dictionary[aliasKey]) {
      return resolveAlias(dictionary[aliasKey], dictionary);
    }
  }
  return value;
}

function resolveDictionary(source: Record<string, string>, contextDict: Record<string, string>): Record<string, string> {
  const resolved: Record<string, string> = {};
  for (const key in source) {
    resolved[key] = resolveAlias(source[key], contextDict);
  }
  return resolved;
}

// 辞書の構築
const lightDict = { ...flatPrimitive, ...flatSemanticLight };
const darkDict = { ...flatPrimitive, ...flatSemanticDark };

const resolvedSemanticLight = resolveDictionary(flatSemanticLight, lightDict);
const resolvedSemanticDark = resolveDictionary(flatSemanticDark, darkDict);
const resolvedButtonLight = resolveDictionary(flatButton, lightDict);
const resolvedButtonDark = resolveDictionary(flatButton, darkDict);

// 3. CSSの生成
function generateCssBlock(selector: string, dicts: Record<string, string>[]) {
  let css = `${selector} {\n`;
  for (const dict of dicts) {
    for (const key in dict) {
      css += `  --${key}: ${dict[key]};\n`;
    }
  }
  css += `}\n\n`;
  return css;
}

let finalCss = `/* Auto-generated by Design Harness. DO NOT EDIT. */\n\n`;

// Primitive (テーマ共通)
finalCss += generateCssBlock(':root', [flatPrimitive]);

// Light Theme (デフォルト & data-theme="light")
finalCss += generateCssBlock(':root, [data-theme="light"]', [resolvedSemanticLight, resolvedButtonLight]);

// Dark Theme (data-theme="dark")
finalCss += generateCssBlock('[data-theme="dark"]', [resolvedSemanticDark, resolvedButtonDark]);

// 4. 出力
fs.writeFileSync(OUTPUT_FILE, finalCss, 'utf8');
console.log(`✅ CSS Variables generated at: ${OUTPUT_FILE}`);
